name: Encoder test action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Rye
      uses: sksat/setup-rye@v0.8.0
    - name: Change directories
      run: |
        cd encoder
        rye run python encoder.py "aaabbc"
    - name: Sync dependencies
      run: rye sync
    - name: Run tests
      run: rye run pytest -v
