name: Encoder test action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Validate directory
      run: ls
    - name: Change directories
      run: cd encoder/
    - name: Validate directories
      run: ls
    - name: Change directories
      run: cd encoder/
    - name: Validate directories
      run: ls
